angular.module("list",[])
.constant("pageLen",5)
.controller("listCtrl",["$scope","$http","$routeParams","pageLen",function($scope,$http,$routeParams,pageLen){
	$scope.pageLen=pageLen;
	console.log($scope.pageLen);
	$http.get("http://127.0.0.1/list.php?page=0&pageLen="+$scope.pageLen+"&sort=desc&typeid="+$routeParams.id)
	.success(function(res){
		$scope.listData=res.data;
	})
	$scope.typeid=$routeParams.id;
}])